### ISSUE TITLE
Third Party Repository

### ISSUE THREAD

**Issue by CounterPillow** [CounterPillow/quartz64-images#12]
To distribute our device tree package, we need a third party repository.

- [ ] ~~Write a server-side app that receives package pushes over HTTP(S) and rebuilds a repo~~
  * ~~Maybe use flask for this~~
  * ~~Figure out which tooling is the easiest to integrate for generating Debian repository metadata and such~~
- [ ] Set up aptly on a dedicated subdomain with HTTP basic auth on the reverse proxy for the API
- [ ] Split the device tree packaging into its own workflow
- [ ] Integrate the repo upload + publishing into the GitHub Actions Workflow with a secret key
  * Perhaps with an input setting to say "publish this run"
- [ ] Add repository URL to the image's sources list

**Comment by neggles** [comment]
perhaps [aptly](https://aptly.info) hosted in an S3-type object storage bucket, or just behind nginx on a free oci instance?

**Comment by CounterPillow** [comment]
Thanks for pointing me towards aptly. I'm unlikely gonna be using anything S3-style, but just run this on my server behind nginx.

**Comment by neggles** [comment]
No problem :) I spent quite some time trying to find a straightforward way to manage apt repos, and it seems to be pretty decent though I've not used it for a great deal yet.

I do like that it doesn't try to be a webserver or load you down with all kinds of unnecessary garbage.

**Comment by diederikdehaas** [comment]
I was wondering why anyone would write a custom solution for something which has several implementations right in the Debian archives.  
I have no practical experience with any of them, but ``aptly`` is also used in Debian Salsa's CI pipelines, so it seems like a good choice :-)

**Comment by CounterPillow** [comment]
The custom solution is needed anyway to push the image artifacts onto a presentable webpage. This is needed because GitHub artifacts expire after 90 days, and are only available to download for logged-in users. I was considering making the Debian repo rebuild stuff part of that, but will probably just go with aptly; I've already started on the Flask app for presenting image artifacts though.

**Comment by diederikdehaas** [comment]
I may be more inclined to *use Debian stuff/packages whenever possible* then others ;-)  
But for the rest, like artifacts download, you *do* need custom solution.
