### ISSUE TITLE
Additional Device Trees

### ISSUE THREAD

**Issue by CounterPillow** [CounterPillow/quartz64-images#13]
- [x] Build SOQuartz Blade device tree in package
- [x] Build SOQuartz Blade images
- [x] Build SOQuartz Model A device tree in package
- [x] Build SOQuartz Model A images

**Comment by diederikdehaas** [comment]
Why build the Device Trees in (separate) package(s)?  
See also https://salsa.debian.org/kernel-team/linux/-/merge_requests/589

**Comment by CounterPillow** [comment]
So I'm not bound by the speed of Debian's kernel team. If I do go with Debian's experimental kernel and use their device trees, then I wouldn't have blade images or SOQuartz A baseboard images for a long time, which is bad for products people can buy and have already bought.

**Comment by diederikdehaas** [comment]
Finally got some clarity: those changes may not make it into Bookworm's kernel (and thus DT) at all. It *could* happen if one of the upstream 6.1 maintainers decides to add them, then they'd end up in Debian's kernel too.  
But if they don't, then Bookworm's kernel will not have it (at all). So it's safer to do your own thing.
