### ISSUE TITLE
RAM logging ?

### ISSUE THREAD

**Issue by nathmo** [CounterPillow/quartz64-images#24]
hey just to make sure, there is no form of RAM logging and it's up to the user to install log2ram and such if they need it ?
might be worth mentionning it somewhere

(btw. GG for this repo, i  tested a few image and your stand out by it's simplicity and ease of use while having support for the 8Gb of ram and ZFS) (~~I still need to ensure PCIe extension board works~~ -> It works !)

**Comment by CounterPillow** [comment]
it's indeed up to the user to install this, it should be just like you'd set it up on Debian. I don't plan to include too much additional stuff by default aside from what's needed to get a standard Debian live system running.

I'm glad the images are working out well for you :)
