### ISSUE TITLE
network -> Static IP 

### ISSUE THREAD

**Issue by nathmo** [CounterPillow/quartz64-images#25]
I not sure about how to setup the static IP address.
usually, it's under `/etc/network/interfaces` but the file only contain 
```
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source /etc/network/interfaces.d/*
```
and there is nothing under interfaces.d
should I just add my config in `/etc/network/interfaces` or I missed somthing else ?
my network config would be this :

```
auto end0
iface end0 inet static
 address 192.168.1.10
 netmask 255.255.255.0
 gateway 192.168.1.1
```

well it worked so it's all good

**Comment by nathmo** [comment]
i'm sorry to reopen but i have some DNS issues... I tried to edit  `/etc/resolv.conf` and to add `dns-nameservers 8.8.8.8` to `/etc/network/interfaces`
but etc/resolv.conf keep being reset so i dont know how to fix it and i'm scared of breaking everything

**Comment by nathmo** [comment]
the fix was to unlink the simlink on /etc/resolv.conf and recreate it.
`sudo unlink /etc/resolv.conf`
`sudo nano /etc/resolv.conf `
add this in the file :
```
nameserver 1.1.1.1
nameserver 8.8.8.8
```
`sudo systemctl restart systemd-resolved`

**Comment by neggles** [comment]
Highly recommend using either `systemd-networkd`, `netplan`, or `NetworkManager` to configure networking - `/etc/network/interfaces` has been deprecated for almost 10 years now and (as you've discovered) is not particularly intuitive.

> the fix was to unlink the simlink on /etc/resolv.conf and recreate it.

Be careful with this - next time you reboot, `systemd` may overwrite that with the original symlink and you'll be back to square one...

**Comment by nathmo** [comment]
okay i think i get it. if anybody else read this : see #26
