### ISSUE TITLE
NAS setup using plebian 

### ISSUE THREAD

**Issue by nathmo** [CounterPillow/quartz64-images#26]
hey, 
I made an installation guide to a NAS / home server to self-host docker container using plebian as a base OS. I believe it might be of interest to the peoples who download your image.

https://github.com/nathmo/Quartz64_NAS/blob/main/README.md

**Comment by CounterPillow** [comment]
Hi,

I'd be happy to link this in a "further reading" section of RUNNING.md, but I found a few issues:

1. static IP should be set through NetworkManager, not interfaces. We use NetworkManager by default as it is a lot more flexible with binding to interfaces and doesn't block bootup if no cable is plugged in. You can [use nmcli for setting up a static IP](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configuring_ip_networking_with_nmcli#sec-Adding_and_Configuring_a_Static_Ethernet_Connection_with_nmcli), or disable NetworkManager *before* switching back to Debian interfaces.
2. Manual DNS servers shouldn't be set in resolv.conf but [through systemd-resolved](https://wiki.archlinux.org/title/Systemd-resolved#Manually), which is the used DNS resolver
3. Consider whether you even need a static IP. Plebian brings up multicast DNS by default, you can just ssh into the hostname of the board with `.local` appended, assuming your system is able to resolve mDNS.

**Comment by nathmo** [comment]
i will fix that ^^ thanks for the input. i wasnt aware there was nmcli

**Comment by CounterPillow** [comment]
I've added the article to a "Further Reading" section of "RUNNING.md", thanks for taking the time writing it!
