### ISSUE TITLE
Alpine based images

### ISSUE THREAD

**Issue by adminy** [CounterPillow/quartz64-images#27]
I noticed that this is in the plans:

https://github.com/Plebian-Linux/quartz64-images/blob/33c84b56ac89c7bbfaa5654abe8fa6f9cc4b30dd/README.md#L48

Debos recently added support for arch linux images, and I wonder in order not to be completely locked into debian based, we could try alpine or arch just to have it more generalised going forwards?

**Comment by CounterPillow** [comment]
Arch is a hard no because the Arch Linux ARM project is unmaintained. Alpine is a possibility if debos adds support for it.
