### ISSUE TITLE
filesystem resize did not occur on first boot

### ISSUE THREAD

**Issue by julianblanco** [CounterPillow/quartz64-images#30]
Hello,

PINE64 SOQuartz on the pine64 carrier board.
Just flashed v2023-03-09-1 to a 128gb microsd

boots up cleanly but does not resize filesystem.

Also: If possible can you add an issue template to CONTRIBUTING.md just so in the future I make sure i get all the necessary details on the first try :)

Thanks for putting this together. Looking forward to trying out Plebian!

**Comment by CounterPillow** [comment]
> on the pine64 carrier board.

There are two carrier boards by PINE64, which one do you mean?

**Comment by julianblanco** [comment]
Model-A Baseboard

**Comment by CounterPillow** [comment]
Thanks, I managed to reproduce this issue, and will look into it further

**Comment by CounterPillow** [comment]
Found the problem, we need to regenerate initramfs in our debos config and this was inadvertently left out when the kernel install (which did that) was removed.
