### ISSUE TITLE
Unable to Initialize NVMe SSD on plebian-debian-bookworm-soquartz-blade (v2023-07-19-1) Image

### ISSUE THREAD

**Issue by Morten-Renner** [CounterPillow/quartz64-images#42]
(I am uncertain if this is an issue or just my half-knowledge / please close if this feels to help deskish. I also think that this might is an kernel issue in 6.1 but I am just not sure.)

With the **plebian-debian-bookworm-soquartz-blade (v2023-07-19-1)** image I cant get the m.2 nvme (Kingston NV1 NVMe PCIe SSD 250G) to work (tried also 1 from Samsung but dmesg had a similar output).

```
pleb@plebian-soquartz-blade:~$ sudo dmesg | grep "nvme"
[    5.737916] nvme nvme0: pci function 0000:01:00.0
[    5.738473] nvme 0000:01:00.0: enabling device (0000 -> 0002)
[   36.243017] nvme nvme0: Device not ready; aborting initialisation, CSTS=0x0
[   36.243685] nvme nvme0: Removing after probe failure status: -19
```
Please note the wrong size, but still the correct manufacturer:
```
pleb@plebian-soquartz-blade:~$ lspci -nn
00:00.0 PCI bridge [0604]: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor [1d87:3566] (rev 01)
01:00.0 Non-Volatile memory controller [0108]: Kingston Technology Company, Inc. SNVS2000G [NV1 NVMe PCIe SSD 2TB] [2646:500e] (rev 01)
```

```
pleb@plebian-soquartz-blade:~$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
mmcblk0     179:0    0 59.4G  0 disk
|-mmcblk0p1 179:1    0   32M  0 part
`-mmcblk0p2 179:2    0 59.4G  0 part /
```

This "nvme nvme0: Device not ready; aborting initialisation, CSTS=0x0" is essentially saying nothing to me. I now have no point of researching further into this issue :/

Essentially I just want to know if you have an idea or already stumbled upon a similar issue?

Thank you in advance.

**Comment by CounterPillow** [comment]
The one time I've seen issues with disappearing/resetting NVMe drives on SOQuartz Blade was when I used an unsuitable power supply. Specifically, I was powering it through a USB-to-barrel-jack cable from a USB power meter connected to a 3A USB supply. Turns out one of these components caused issues, and directly powering it from a 5V3A non-USB supply worked just fine.

**Comment by Morten-Renner** [comment]
Thanks for your help. I was unable to fix this with and I'm now switching to a different manufacturer. I will close this since this only seems to affect me and it is likely just faulty hardware.
