### ISSUE TITLE
Using Remote Desktop or VNC 

### ISSUE THREAD

**Issue by b-morgan** [CounterPillow/quartz64-images#43]
I have a working Gnome Desktop on my Quartz64 model B but I would like to connect to the system using either Remote Desktop (xrdp) or VNC (x11vnc).

xrdp brings up a login screen but after entering my credentials, I get a black window which disappears. If there is a log somewhere, please let me know where and I'll add it.

x11vnc installs but I can't get it to start (i.e. no listening ports in the 5900-5910 range). A link to instructions would be very helpful.

**Comment by CounterPillow** [comment]
That's a question about Debian usage, there is nothing device specific about this. Therefore I am not the right person to answer this.
